package com.cowsbulls.src.objects;
// Generated 13.03.2015 21:07:39 by Hibernate Tools 4.3.1

import com.cowsbulls.src.utils.SQLConstants;
import javax.persistence.*;




/**
 * Player generated by hbm2java
 */
@Entity
@Table(name = "player")
public class Player  implements java.io.Serializable {

    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    @Column(name = "id")
    private Integer id;
    
    @Column(name = "login", length = 50)
    private String login;
    
    @Column(name = "password", length = 50)
    private String password;
    
    @Column(name = "name", length = 50)
    private String name;
    
    @Column(name = "surname", length = 50)
    private String surname;
    
    @Column(name = "country", length = 50)
    private String country;
    
    @Column(name = "age")
    private Integer age;
    
    @Column(name = "gender")    
    private Integer gender;
    
    @Column(name = "avatar")    
    private byte[] avatar;
    
    @Column(name = "type")  
    private Integer type;
    
    @Column(name = "wins")  
    private int wins;
    
    @Column(name = "loses")  
    private int loses;
    
    @Column(name = "status")
    private int status;
    
    @Column(name = "number")
    private String number;
    
    public Player() {
        this.login = "";
        this.password = "";
        this.wins = 0;
        this.loses = 0;
        this.status = SQLConstants.PLAYER_STATUS_OFFLINE;
        this.number = "";
    }

	
    public Player(String login, String password, int wins, int loses, int status) {
        this.login = login;
        this.password = password;
        this.wins = wins;
        this.loses = loses;
        this.status = status;
        this.number = "";
    }
    public Player(String login, String password, String name, String surname, 
                String country, Integer age, Integer gender,
                byte[] avatar, Integer type,
                int wins, int loses, int status,
                String number) {
       this.login = login;
       this.password = password;
       this.name = name;
       this.surname = surname;
       this.country = country;
       this.age = age;
       this.gender = gender;
       this.avatar = avatar;
       this.type = type;
       this.wins = wins;
       this.loses = loses;
       this.status = status;
       this.number = number;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }
    public Integer getAge() {
        return this.age;
    }
    
    public void setAge(Integer age) {
        this.age = age;
    }
    public Integer getGender() {
        return this.gender;
    }
    
    public void setGender(Integer gender) {
        this.gender = gender;
    }
    public byte[] getAvatar() {
        return this.avatar;
    }
    
    public void setAvatar(byte[] avatar) {
        this.avatar = avatar;
    }
    public Integer getType() {
        return this.type;
    }
    
    public void setType(Integer type) {
        this.type = type;
    }
    public int getWins() {
        return this.wins;
    }
    
    public void setWins(int wins) {
        this.wins = wins;
    }
    public int getLoses() {
        return this.loses;
    }
    
    public void setLoses(int loses) {
        this.loses = loses;
    }
    public int getStatus() {
        return this.status;
    }
    
    public void setStatus(int status) {
        this.status = status;
    }

    public boolean CheckValues()
    {
        return !this.login.isEmpty() &&
               !this.password.isEmpty();
    }

    /**
     * @return the number
     */
    public String getNumber() {
        return number;
    }

    /**
     * @param number the number to set
     */
    public void setNumber(String number) {
        this.number = number;
    }
}


